### ISSUE TITLE
Feuille aide-mémoire pour Intra A2018

### ISSUE THREAD

**Issue by gabrielcrepeault** [gabrielcrepeault/IARD1#2]
@NicholasLangevin , penses-tu être capable d'intégrer ta feuille de formules à ce document, en annexe? Le tout peut se faire avec le package [pdfpages](https://stackoverflow.com/questions/2739159/inserting-a-pdf-file-in-latex).

**Comment by NicholasLangevin** [comment]
Oui, je vais mettre le frame aujourd'hui et commencer a ajouter des formuls, si tu veut en rajouter aussi tu est la bienvenu !
